name: Utopiart Studios
favicon: null
layout_spectrum: 0.05961850006133318
typography_spectrum: 0.5475604853127152
title: 'Utopiart Studios - 3D Printing, 3D Scanning, Prop Work, Photography and More!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#000000'
    - '#414547'
    - '#ff001a'
    - '#e75354'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
