name: Utopiart Studios
favicon: null
layout_spectrum: 0.05961850006133318
typography_spectrum: 0.5475604853127152
title: 'Utopiart Studios - 3D Printing, 3D Scanning, Prop Work, Photography and More!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.33174389647319913
  lightness: 0.0620466023683548
  saturation: 0.7902853197883815
  rhythmicContrast: 0.8622652322519571
purpose: []
